export const CHANGE_TYPE_SEARCH = "CHANGE_TYPE_SEARCH";
export const CHANGE_AREA_SEARCH = "CHANGE_AREA_SEARCH";
export const CHANGE_SORT_SEARCH = "CHANGE_SORT_SEARCH";
export const GET_PRODUCTS = "GET_PRODUCT";
